name: Code Quality & Security Checks

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  sast-bash:
    name: Run Semgrep (SAST Security)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Run Semgrep
        run: |
          docker run --rm -v "${{ github.workspace }}:/src" returntocorp/semgrep semgrep scan --config=auto --error

  lint-bash:
    name: Run ShellCheck (Linter)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@00ca84fe1b3011531a02f98f93462f4836016bc3

  format-bash:
    name: Run Shfmt (Formatter)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Run Shfmt
        uses: mfinelli/setup-shfmt@9463428d09f7a552309197a99f1fae92976be39a
      - name: Run Shfmt
          # -d show differences and return an error if it's not well formatted
          # -i number of spaces to use for indentation (default is 4)
        run: shfmt -d -i 4 .